### ISSUE TITLE
Attendance Page issue

### ISSUE THREAD

**Issue by mohamedashic** [IlahiTechnologies/bugs-to-fix#55] opened 2021-04-22 13:03 UTC
Students also can scan qr code and make attendance present.

https://drive.google.com/open?id=1IWTO5gIFXYRcIIQb-xFXJH8hJWJtJscA

**Comment by SasiZets** [comment] 2021-04-22 16:04
this is a duplicate of #54 kindly close this @mohamedashic

**Closed** 2021-07-15 11:27 UTC
Labels: duplicate, invalid
